### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 18715: character maps to <undefined>

### ISSUE THREAD

**Issue by ExtEEd** [TradeMaster-NTU/TradeMaster#188]
Windows 10, Anaconda

(tmaster) D:\>pip install git+https://github.com/TradeMaster-NTU/TradeMaster.git
Collecting git+https://github.com/TradeMaster-NTU/TradeMaster.git
  Cloning https://github.com/TradeMaster-NTU/TradeMaster.git to c:\users\user\appdata\local\temp\pip-req-build-ehfyt5hh
  Running command git clone --filter=blob:none --quiet https://github.com/TradeMaster-NTU/TradeMaster.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-ehfyt5hh'
  Resolved https://github.com/TradeMaster-NTU/TradeMaster.git to commit d9737946584d9ea75665684fde03a7db47cb79b5
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-req-build-ehfyt5hh\setup.py", line 4, in <module>
          long_description = fh.read()
        File "D:\Programs\Anaconda\envs\tmaster\lib\encodings\cp1251.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 18715: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sherryfans777** [comment]
Maybe you can try to download as a zip in the web page.  And use the command cd: to switch to your decompression path. I don’t understand it very well and I hope it can help you.
